#include "client.h"

CVARlist cvar;

//=======================================================================================	

void CVARlist::init()
{
	#define INITCVAR(name,value) cmd.AddCvarFloat(#name, &##name );##name=##value;

	INITCVAR(aim_activate,1.0)
	INITCVAR(aim_team,0.0)
	INITCVAR(aim_mode,1.0) // 1 - By Distance; 2 - By FOV
	INITCVAR(aim_shield,0.0)
	INITCVAR(aim_silent,0.0)
	INITCVAR(aim_psilent,0.0)
	INITCVAR(aim_auto,0.0)
	INITCVAR(aim_auto_fov,60.0)
	INITCVAR(aim_knf_attack,2.0)
	INITCVAR(aim_auto_punch,0.0)
	INITCVAR(aim_color,1.0)
	INITCVAR(aim_drawaim,0.0)
	INITCVAR(aim_id_mode,1.0)
	INITCVAR(aim_x_duck,5.0)
	INITCVAR(aim_y_duck,2.0)
	INITCVAR(aim_z_duck,25.0)
	INITCVAR(aim_x_stand,5.0)
	INITCVAR(aim_y_stand,2.0)
	INITCVAR(aim_z_stand,22.0)
	INITCVAR(aim_x_jump,2.0)
	INITCVAR(aim_y_jump,5.0)
	INITCVAR(aim_z_jump,13.0)
	INITCVAR(aim_x_duckmove,5.0)
	INITCVAR(aim_y_duckmove,2.0)
	INITCVAR(aim_z_duckmove,25.0)
	INITCVAR(aim_x_running,5.0)
	INITCVAR(aim_y_running,2.0)
	INITCVAR(aim_z_running,22.0)
	INITCVAR(aim_x_walking,5.0)
	INITCVAR(aim_y_walking,2.0)
	INITCVAR(aim_z_walking,22.0)

	INITCVAR(knf_distattack,72.0)
	INITCVAR(knf_distattack2,64.0)
	INITCVAR(knf_attack,2.0)
	INITCVAR(knf_activate,0.0)
	INITCVAR(knf_fov,40.0)

	INITCVAR(trigger_activate,0.0)
	INITCVAR(trigger_fov,7.0)

	INITCVAR(norecoilvalue,0.0)
	INITCVAR(norecoil,1.0)
	INITCVAR(nospread,1.0)
	INITCVAR(nospreaddraw,0.0)
	INITCVAR(norecoildraw,0.0)
	INITCVAR(norecoil_visual,0.0)
	INITCVAR(norecoil_visible,0.0)
	INITCVAR(nospread_visible,0.0)

	INITCVAR(burst_ftime,0.1f)
	INITCVAR(burst_dtime,0.0)
	INITCVAR(burst_sdelay,0.0)
	INITCVAR(burst_rdelay,0.0)

	INITCVAR(wavspeed,1.0)
	INITCVAR(wavaspeed,1.0)
	INITCVAR(wavrspeed,1.0)

	INITCVAR(misc_auto_pistol,1.0)
	INITCVAR(misc_rem_flash,1.0)
	INITCVAR(misc_name,1.0)
	INITCVAR(misc_weapon,0.0)
	INITCVAR(misc_esp_back,0.0)
	INITCVAR(misc_tint,0.55f)
	INITCVAR(misc_esp_team,0.0)
	INITCVAR(misc_box,0.0)
	INITCVAR(misc_box_width,0.3f)
	INITCVAR(misc_box_height,0.9f)
	INITCVAR(misc_box_size_up,40.0)
	INITCVAR(misc_box_size_down,40.0)
	INITCVAR(misc_sequence,0.0)
	INITCVAR(misc_hud_info,1.0)
	INITCVAR(misc_soundesp,0.0)
	INITCVAR(misc_soundtime,1.5)
	INITCVAR(misc_snapshot_time,10.0)
	INITCVAR(misc_radar,1.0)
	INITCVAR(misc_radars,50.0)
	INITCVAR(misc_radarpoints,0.0)
	INITCVAR(misc_wall,0.0)
	INITCVAR(misc_chasecam,0.0)
	INITCVAR(misc_health,0.0)
	INITCVAR(misc_norefresh,0.0)
	INITCVAR(misc_hud,1.0)   
	INITCVAR(misc_nohud,1.0)   
	INITCVAR(misc_spin,0.0)
	INITCVAR(misc_spinspeed,20.0)
	INITCVAR(misc_nosky,1.0)
	INITCVAR(misc_lambert,1.0)
	INITCVAR(misc_quake,0.0)
	INITCVAR(misc_wirewall,0.0)
	INITCVAR(misc_sayid,0.0)
	INITCVAR(misc_nightmode,0.0)
	INITCVAR(misc_aa_pitch,0.0)
	INITCVAR(misc_aa_yaw,0.0)

	INITCVAR(kzstrafehack,1.0)
	INITCVAR(kzstrafeautodir,0.0)
	INITCVAR(kzgroundstrafe,0.0)
	INITCVAR(kzbhop,1.0)
	INITCVAR(kzjumpbug,0.0)
	INITCVAR(kzfastrun,0.0)
	INITCVAR(kzstrafe_helper,1.0)
	INITCVAR(kzslowdown,0.0)
	INITCVAR(kzshow_kz,0.0)
	INITCVAR(kzstrafe_dir,1.0)
	INITCVAR(kzstrafe_crazy,0.0)
	INITCVAR(kzstrafe_invisible,0.0)
	INITCVAR(kzstrafe_speed,69.0)
	INITCVAR(kzstrafe_sidemove,437.8928f)
	INITCVAR(kzstrafe_angle,30.0)
	INITCVAR(kzfastrun_nsd,0.0)
	INITCVAR(kzgstrafe_standup,0.0)
	INITCVAR(kzgstrafe_bhop,1.0)
	INITCVAR(kzgstrafe_nsd,0.0)
	INITCVAR(kzbhop_nsd,0.0)
	INITCVAR(kzbhop_autoduck,0.0)
	INITCVAR(kzbhop_cnt_rand_min,0.0)
	INITCVAR(kzbhop_cnt_rand_max,12.0)
	INITCVAR(kzbhop_cnt_rand,1.0)
	INITCVAR(kzbhop_cnt,4.0)
	INITCVAR(kzjumpbugauto,0.0)
	INITCVAR(kzjumpbugslow,100.0)
	INITCVAR(kzjumpbugslowspeed,1.0)
	INITCVAR(kzstrafe_helper_boost,1.0)
	INITCVAR(kzstrafe_helper_add_strafe,1.0)
	INITCVAR(kzstrafe_helper_max_strafe_rand,0.0)
	INITCVAR(kzstrafe_helper_max_strafe_min,3.0)
	INITCVAR(kzstrafe_helper_max_strafe_max,6.0)
	INITCVAR(kzstrafe_helper_max_strafe,6.0)
	INITCVAR(kzstrafe_helper_main,30.0)
	INITCVAR(kzstrafe_helper_move_rand,1.0)
	INITCVAR(kzstrafe_helper_move_rand_min,50.0)
	INITCVAR(kzstrafe_helper_move_rand_max,400.0)
	INITCVAR(kzstrafe_helper_move,400.0)
	INITCVAR(kzfps_helper,0.0)
	
	INITCVAR(auto_direction,1.0)
	INITCVAR(auto_jump,1.0)

	INITCVAR(rush,0.0)
	INITCVAR(way_on,0.0)
	INITCVAR(way_enable,1.0)
	INITCVAR(way_draw,1.0)
	INITCVAR(way_mode,1.0)
	INITCVAR(way_fov,45.0)
	INITCVAR(record_dist,55.0)
	INITCVAR(way_mindist,50.0)
	INITCVAR(way_maxdist,150.0)
	INITCVAR(way_drawvisuals,1.0)
	INITCVAR(way_radardist,2500.0)


	INITCVAR(color_red,0.0)
	INITCVAR(color_green,0.0)
	INITCVAR(color_blue,1.0)
}

void CVARlist::Save()
{
	ofstream ofs( getHackDirFile("cvar.ini").c_str() );
	cmd.save_cvars(ofs);
	ofs.close();
}

void CVARlist::Load()
{
	if( !fileExists(getHackDirFile("cvar.ini").c_str()) ) return;
	cmd.load_cvars();
}
